import type { Project } from "@/lib/types";

/** Display order. The ledger index (01, 02, …) is derived from position. */
export const projects: Project[] = [
  {
    slug: "canopy",
    title: "Canopy",
    org: "Personal",
    year: "2026",
    status: "In progress",
    featured: true,
    stack: ["Expo", "React Native", "TypeScript", "SQLite", "Supabase", "RevenueCat"],
    summary:
      "An iOS app for people with ideas. A local-first private notebook paired with a public board where an AI and other people score each idea side by side, and every released idea carries a verified outcome. Built solo in about a week, and it's on Apple's TestFlight right now.",
    description:
      "Canopy, an iOS app pairing a private idea notebook with a public board where AI and other people score ideas side by side. Built solo in about a week.",
    role: "Designer and developer",
    timeline: "First commit Aug 28, 2026. On Apple's TestFlight right now.",
    team: "Solo",
    images: [
      { src: "/projects/canopy/seeds.png", alt: "Canopy Seeds screen listing private ideas with AI scores", width: 588, height: 1280, caption: "Seeds: your private ideas, each with its AI score." },
      { src: "/projects/canopy/canopy.png", alt: "The Canopy public board with ideas from other builders", width: 588, height: 1280, caption: "The Canopy: the public board." },
      { src: "/projects/canopy/profile.png", alt: "Profile screen with launched, building, thinking, and fallen counts", width: 588, height: 1280, caption: "You: your ideas by stage, plus patterns the AI notices." },
    ],
  },
  {
    slug: "cfsm-ops",
    title: "Operations Platform",
    org: "Computers For Schools Manitoba",
    year: "2020",
    status: "Shipped",
    featured: true,
    stack: ["Laravel 8", "MySQL", "mPDF"],
    images: [
      {
        src: "/projects/cfsm-ops/home.png",
        alt: "DatabaseWEB home dashboard in a test environment, showing weekly cataloguing and production counts",
        width: 1922,
        height: 1080,
        caption: "The home dashboard (test environment): weekly counts for cataloguing, pre-production, and orders, with a leaderboard per staff member.",
      },
      {
        src: "/projects/cfsm-ops/donations.png",
        alt: "Cataloguing a material from a donation load",
        width: 1924,
        height: 1042,
        caption: "Cataloguing a single item out of a donation load, with storage devices attached to it.",
      },
      {
        src: "/projects/cfsm-ops/materials.png",
        alt: "Material lookup with a computer's details open",
        width: 1924,
        height: 1042,
        caption: "Material lookup. Every item has its own record with specs, storage, history, and where it is now.",
      },
      {
        src: "/projects/cfsm-ops/orders.png",
        alt: "Viewing an order with its product counts and print options",
        width: 1924,
        height: 1042,
        caption: "An order in production, with product counts, reception view, and print options for labels and order sheets.",
      },
      {
        src: "/projects/cfsm-ops/rma.png",
        alt: "New RMA form",
        width: 1924,
        height: 1042,
        caption: "Opening an RMA: the material, the reported problem, who brought it in, and what came with it.",
      },
    ],
    summary:
      "Replaced an aging Microsoft Access database with one Laravel app for donations, inventory, warehousing, orders, RMAs, and recycling. Over 100,000 inventory records, thousands of orders, and still running the organization today.",
    description:
      "Laravel operations platform for Computers For Schools Manitoba, still in daily use. Donations, inventory, orders, RMAs, and recycling, 100,000+ records.",
    role: "Sole developer, built from scratch",
    timeline: "Built Aug 2020 – Jun 2022, supported on contract to Aug 2024, still in use today",
    team: "Solo, with the Executive Director and warehouse, refurbishment, and admin staff",
  },
  {
    slug: "member-platform",
    title: "Member Management & Events Platform",
    org: "Manitoba Métis Federation",
    year: "2026",
    status: "Shipped",
    featured: true,
    confidential: true,
    stack: ["Laravel 13", "Inertia", "React 19", "PostgreSQL", "Azure AD SSO", "OAuth2"],
    images: [
      { src: "/projects/member-platform/dashboard.png", alt: "Dashboard with the next event, member totals, and new-member counts by month, quarter, and fiscal year", width: 1600, height: 1000, caption: "The dashboard: next event, member totals, and new members by month, quarter, and fiscal year. Sample data." },
      { src: "/projects/member-platform/members-list.png", alt: "Members list with filters for citizenship, verification, and pending updates, names blurred", width: 1600, height: 1120, caption: "The members list with its filters. Names and citizen numbers are blurred." },
      { src: "/projects/member-platform/member-detail.png", alt: "Member detail panel showing a re-registration alert with the submitted value beside the current one", width: 1600, height: 1000, caption: "A member who re-registered with a different email. Staff accept or dismiss each changed field." },
      { src: "/projects/member-platform/event-day.png", alt: "Event page with attendance counts, an on-site tally, and the registration list, names blurred", width: 1600, height: 1150, caption: "An event on the day: who is interested, who attended, and who is on site right now." },
      { src: "/projects/member-platform/events.png", alt: "Events list with upcoming and completed counts and a quick scan button for the next event", width: 1600, height: 1000, caption: "The events list, with quick scan and directions for whatever is next." },
    ],
    summary:
      "The system of record for one of the organization's departments. Over 2,000 members, their regional locals, and every event they run. Staff sign in with their existing work accounts, and the public website pulls member data straight from it instead of someone re-typing it.",
    description:
      "Member management and events platform for the Manitoba Métis Federation. 2,000+ members, Azure AD sign-in, and an OAuth2 API feeding the public site.",
    role: "Sole developer",
    timeline: "Shipped 2026, ongoing support",
    team: "Solo, with the department's director and frontline staff as stakeholders",
  },
  {
    slug: "graduation-portal",
    title: "Graduation Ceremony Portal",
    org: "Manitoba Métis Federation",
    year: "2025",
    status: "Shipped",
    featured: true,
    confidential: true,
    stack: ["SvelteKit", "Convex", "Service Worker"],
    images: [
      {
        src: "/projects/graduation-portal/projector-graduate.png",
        alt: "Projector screen showing a graduate's name and department after their card was scanned",
        width: 1920,
        height: 1080,
        caption: "The projector screen the moment a card is scanned at the stage.",
      },
      {
        src: "/projects/graduation-portal/gown-rented.png",
        alt: "Gown rental screen with a student's record, gown size, and a return gown button",
        width: 1400,
        height: 800,
        caption: "Gown check-out: scan a card, pick the size, and one button toggles rented or returned.",
      },
      {
        src: "/projects/graduation-portal/roster.png",
        alt: "Import and export page with a CSV import, an add student form, and the graduate table",
        width: 1400,
        height: 1300,
        caption: "The import page. The graduate list comes in as a CSV and goes back out the same way. The roster is blurred.",
      },
      {
        src: "/projects/graduation-portal/projector-idle.png",
        alt: "Projector idle screen reading LRC Graduation, scan student ID",
        width: 1920,
        height: 1080,
        caption: "The idle screen between graduates.",
      },
      {
        src: "/projects/graduation-portal/lock.png",
        alt: "Access code prompt shown before any page of the app",
        width: 1400,
        height: 520,
        caption: "Every station has to be unlocked with an access code first.",
      },
    ],
    summary:
      "Scan a student card to check a gown out or back in, and scan again at the stage to put their name on the projector. Handled over 150 graduates across two ceremonies, and built to keep working if the venue Wi-Fi drops.",
    description:
      "Offline-capable graduation ceremony app on SvelteKit and Convex. Barcode gown check-in and a live stage scanner that puts each graduate on the projector.",
    role: "Sole developer",
    timeline: "Two consecutive graduation ceremonies",
    team: "Solo, built for the department that runs the ceremony and run on-site with their staff",
  },
  {
    slug: "mvlp-website",
    title: "Métis Veterans Legacy Program Website",
    org: "Manitoba Métis Federation",
    year: "2026",
    status: "In progress",
    stack: ["Next.js 16", "React 19", "Strapi 5", "TipTap", "Tailwind 4"],
    images: [
      {
        src: "/projects/mvlp/home.jpg",
        alt: "Home page hero of the Métis Veterans Legacy Program website, with photos blurred",
        width: 1600,
        height: 1000,
        caption: "The home page. Photos are blurred here because they show real people.",
      },
      {
        src: "/projects/mvlp/programs.jpg",
        alt: "Program cards on the home page linking to the Commemoration Program and Recognition Payment",
        width: 1600,
        height: 1000,
        caption: "The two programs the site exists to explain, right below the hero.",
      },
      {
        src: "/projects/mvlp/recipients.jpg",
        alt: "Grid of recognition payment recipient cards pulled from the CMS, with photos and names blurred",
        width: 1600,
        height: 880,
        caption: "Recognition payment recipients, each one a CMS entry. Names and photos are blurred.",
      },
      {
        src: "/projects/mvlp/commissioners.jpg",
        alt: "The Commission page with a commissioner's profile card, portrait and text blurred",
        width: 1600,
        height: 960,
        caption: "The Commission page. Portraits, names, and bios are blurred.",
      },
      {
        src: "/projects/mvlp/eligibility.jpg",
        alt: "Recognition payment eligibility cards for veterans, spouses, and children",
        width: 1600,
        height: 1100,
        caption: "Eligibility rules laid out as three cards instead of a wall of text.",
      },
    ],
    summary:
      "A public website for the program that recognizes WWII Métis Veterans. A Next.js front end on top of a Strapi CMS, so program staff can publish news, recipient profiles, and commemoration projects without a developer.",
    description:
      "Public website for the Métis Veterans Legacy Program. Next.js front end on a Strapi CMS so staff can publish news, recipient profiles, and projects themselves.",
    role: "Sole developer",
    timeline: "Started June 2026, on a staging domain ahead of launch",
    team: "Solo, with the program's staff as content owners",
  },
  {
    slug: "homeland-map",
    title: "Homeland Map",
    org: "Manitoba Métis Federation",
    year: "2026",
    status: "In progress",
    stack: ["Three.js", "TypeScript", "Vite", "Express", "SQLite"],
    images: [
      { src: "/projects/homeland-map/overview.jpg", alt: "3D relief map of Canada in sepia with labelled Red River Métis places across the prairies", width: 1600, height: 1000, caption: "The home view: an extruded, shaded relief of Canada with the places marked." },
      { src: "/projects/homeland-map/batoche.jpg", alt: "Batoche selected on the map, with lines to five connected places labelled by distance and an info panel", width: 1600, height: 1000, caption: "Tap Batoche and the camera flies in and orbits while its connections light up, each labelled with the distance." },
      { src: "/projects/homeland-map/admin.png", alt: "Admin page listing the places with a form for editing one", width: 1600, height: 1000, caption: "The admin page. Places, their write-ups, connections, and pictures are edited here, no code involved." },
    ],
    summary:
      "A 3D relief map of Canada for a museum display. Tap a Red River Métis place and the camera flies in and orbits while its connections light up, each labelled with the distance. Built on Three.js, with a small admin for adding places and pictures.",
    description:
      "3D relief map of Canada for a museum display. Tap a Red River Métis place and the camera flies in while its connections light up. Three.js, Express, SQLite.",
    role: "Sole developer",
    timeline: "Started 2026, working prototype",
    team: "Solo",
  },
];
