import Image from "next/image";
import type { Project } from "@/lib/types";
import { pickShots } from "@/lib/shots";

/**
 * Animated feature card for the Graduation Ceremony Portal. It borrows the
 * projector screen's own look: the navy gradient and the letter-spaced title.
 * A barcode builds up bar by bar, a scan line sweeps across it, and then the
 * projector screen lifts in with the gown and import windows in front. Pure CSS
 * keyframes; see .gf-* in globals.css, generated by scripts/feature-keyframes.mjs.
 */
const BARS = [3, 1, 2, 1, 3, 1, 1, 2, 1, 3];

export function GradFeature({ project }: { project: Project }) {
  const shots = pickShots(project, ["projector-graduate", "gown-rented", "roster"]);
  return (
    <div className="gf relative aspect-video overflow-hidden border border-rule">
      <div className="gf-stage absolute inset-0">
        <div className="gf-brand absolute top-[9%] left-[6%] z-10">
          <span className="gf-title block font-sans text-[1rem] leading-none font-extrabold tracking-[0.3em] text-white sm:text-[1.5rem]">
            GRADUATION
          </span>
          <span className="gf-sub mt-2 block font-sans text-[0.75rem] tracking-[0.1em] text-white/55 sm:mt-3 sm:text-[0.875rem]">
            Scan student ID
          </span>
          <div className="gf-barcode relative mt-4 flex h-6 items-end gap-[3px] sm:mt-5 sm:h-8" aria-hidden="true">
            {BARS.map((w, i) => (
              <span key={i} className={`gf-bar gf-bar-${i + 1} block h-full bg-white/70`} style={{ width: `${w * 2}px` }} />
            ))}
            <span className="gf-scan absolute top-[-4px] bottom-[-4px] left-0 w-[2px] bg-white shadow-[0_0_10px_2px_rgba(255,255,255,0.7)]" />
          </div>
        </div>

        <div className="gf-art absolute inset-0" aria-hidden="true">
          {shots.map((img, i) => (
            <div key={img.src} className={`gf-screen gf-screen-${i + 1}`}>
              <Image
                src={img.src}
                alt=""
                width={img.width}
                height={img.height}
                sizes="(min-width: 768px) 400px, 70vw"
                loading="eager"
                className="h-auto w-full"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
