
const CLIP = "/projects/homeland-map/card-loop";
const POSTER = "/projects/homeland-map/card-loop-poster.jpg";

/**
 * Animated feature card for Homeland Map. Unlike the other cards this one is the
 * app itself: a silent 20 s clip of the model flying in from the overview to St. Vital,
 * tapping it so a few Red River carts set out, turning slowly around it while they roll,
 * and fading to the card's navy before the loop restarts. No client JS; the browser autoplays it muted. Readers who prefer reduced
 * motion get the poster frame instead (see .hf-* in globals.css). The brand block on top
 * plays the same beats as the other cards: name, tag, and a place label, route, and year
 * chip popping in, generated by scripts/feature-keyframes.mjs.
 */
export function HomelandFeature() {
  return (
    <div className="hf relative aspect-video overflow-hidden border border-rule">
      <div className="hf-stage absolute inset-0">
        <video
          className="hf-clip absolute inset-0 h-full w-full object-cover"
          poster={POSTER}
          width={960}
          height={600}
          autoPlay
          muted
          loop
          playsInline
          preload="metadata"
          aria-hidden="true"
          tabIndex={-1}
        >
          <source src={`${CLIP}.mp4`} type="video/mp4" />
        </video>
        {/* Shown only under prefers-reduced-motion, in place of the clip. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={POSTER} alt="" width={960} height={600} loading="lazy" className="hf-still absolute inset-0 hidden h-full w-full object-cover" />
        <div className="hf-wash absolute inset-0" aria-hidden="true" />

        <div className="hf-brand absolute top-[9%] left-[6%] z-10">
          <span className="hf-word block font-serif text-[1.375rem] leading-none text-[#efe9dc] sm:text-[1.75rem]">
            Homeland Map
          </span>
          <span className="hf-tag mt-2 hidden font-mono sm:block text-[0.6875rem] tracking-[0.08em] text-[#b7c3cf] uppercase">
            3D museum exhibit
          </span>
          <div className="mt-4 flex items-center sm:mt-5" aria-hidden="true">
            <span className="hf-pill hf-pill-1 bg-[#53e0d0] text-[#1b2838]">St. Vital</span>
            <span className="hf-route block h-px w-10 bg-[#b7c3cf] sm:w-14" />
            <span className="hf-pill hf-pill-2 border border-[#b7c3cf] bg-[#1b2838] text-[#efe9dc]">1824</span>
          </div>
        </div>
      </div>
    </div>
  );
}
