
const CLIP = "/projects/homeland-map/card-loop";
const POSTER = "/projects/homeland-map/card-loop-poster.jpg";

/**
 * Animated feature card for Homeland Map. Unlike the other cards this one is the
 * app itself: a silent clip recorded from the map of one full orbit around St. Albert,
 * cut to exactly one revolution so the loop is seamless. Readers who prefer reduced
 * motion get the clip's poster frame instead. No
 * client JS; the browser autoplays it muted. Readers who prefer reduced motion get
 * the still frame instead (see .hf-* in globals.css). The brand block on top plays
 * the same beats as the other cards: name, tag, and a place label, route, and
 * distance chip popping in, generated by scripts/feature-keyframes.mjs.
 */
export function HomelandFeature() {
  return (
    <div className="hf relative aspect-video overflow-hidden border border-rule">
      <div className="hf-stage absolute inset-0">
        <video
          className="hf-clip absolute inset-0 h-full w-full object-cover"
          poster={POSTER}
          width={960}
          height={600}
          autoPlay
          muted
          loop
          playsInline
          preload="metadata"
          aria-hidden="true"
          tabIndex={-1}
        >
          <source src={`${CLIP}.mp4`} type="video/mp4" />
        </video>
        {/* Shown only under prefers-reduced-motion, in place of the clip. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={POSTER} alt="" width={960} height={600} loading="lazy" className="hf-still absolute inset-0 hidden h-full w-full object-cover" />
        <div className="hf-wash absolute inset-0" aria-hidden="true" />

        <div className="hf-brand absolute top-[9%] left-[6%] z-10">
          <span className="hf-word block font-serif text-[1.375rem] leading-none text-[#3b2a1a] sm:text-[1.75rem]">
            Homeland Map
          </span>
          <span className="hf-tag mt-2 hidden font-mono sm:block text-[0.6875rem] tracking-[0.08em] text-[#7a5c3a] uppercase">
            3D museum display
          </span>
          <div className="mt-4 flex items-center sm:mt-5" aria-hidden="true">
            <span className="hf-pill hf-pill-1 bg-[#8b2e2e] text-[#f6ecd9]">St. Albert</span>
            <span className="hf-route block h-px w-10 bg-[#8b5a4a] sm:w-14" />
            <span className="hf-pill hf-pill-2 border border-[#c9b48f] bg-[#f6ecd9] text-[#8b2e2e]">510 km</span>
          </div>
        </div>
      </div>
    </div>
  );
}
