import Image from "next/image";
import type { Project } from "@/lib/types";
import { pickShots } from "@/lib/shots";

/**
 * Animated feature card for the Member Management & Events Platform. The app has
 * no public logo, so the brand is its own pink and magenta palette: a square icon
 * whose check mark draws itself, the "Membership & Events" wordmark, and the three
 * status pills from the members table (Citizen, Verified, Sash) popping in. Three
 * app windows then fan in from the right. Pure CSS keyframes; see .mf-* in
 * globals.css, generated by scripts/feature-keyframes.mjs.
 */
export function MemberFeature({ project }: { project: Project }) {
  const shots = pickShots(project, ["dashboard", "members-list", "member-detail"]);
  return (
    <div className="mf relative aspect-video overflow-hidden border border-rule">
      <div className="mf-wash absolute inset-0" aria-hidden="true" />
      <div className="mf-stage absolute inset-0">
        <div className="mf-brand absolute top-[9%] left-[6%] z-10">
          <div className="flex items-center gap-3">
            <span className="mf-icon grid h-8 w-8 place-items-center rounded-md bg-[#c9377f] sm:h-10 sm:w-10">
              <svg viewBox="0 0 24 24" className="h-4 w-4 sm:h-5 sm:w-5" fill="none" aria-hidden="true">
                <path
                  className="mf-check"
                  d="M5 12.5l4.5 4.5L19 7.5"
                  stroke="#fff"
                  strokeWidth="2.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeDasharray="24"
                />
              </svg>
            </span>
            <span className="mf-word font-sans text-[1.125rem] leading-none font-semibold text-[#2a1b24] sm:text-[1.5rem]">
              Membership <span className="font-normal text-[#7a4a62]">&amp; Events</span>
            </span>
          </div>
          <div className="mt-3 flex gap-1.5 sm:mt-4 sm:gap-2" aria-hidden="true">
            <span className="mf-pill mf-pill-1 bg-[#d7f0dd] text-[#1c6b3a]">Citizen</span>
            <span className="mf-pill mf-pill-2 bg-[#1f8a4c] text-white">Verified</span>
            <span className="mf-pill mf-pill-3 bg-[#dbe8fb] text-[#2b5db9]">Sash</span>
          </div>
          <span className="mf-tag mt-4 hidden font-mono sm:block text-[0.6875rem] tracking-[0.08em] text-[#7a4a62] uppercase">
            Member management
          </span>
        </div>

        <div className="mf-art absolute inset-0" aria-hidden="true">
          {shots.map((img, i) => (
            <div key={img.src} className={`mf-window mf-window-${i + 1}`}>
              <Image
                src={img.src}
                alt=""
                width={img.width}
                height={img.height}
                sizes="(min-width: 768px) 360px, 70vw"
                loading="eager"
                className="h-auto w-full"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
