import Image from "next/image";
import type { Project } from "@/lib/types";
import { pickShots } from "@/lib/shots";

/**
 * Animated feature card for the Métis Veterans Legacy Program website. It plays
 * the site's own hero: the pill badge with its pulsing dot, then the two-line
 * heading, on the near-black ground with the indigo wash. Three pages of the site
 * rise in as a stacked deck behind. Pure CSS keyframes; see .vf-* in globals.css,
 * generated by scripts/feature-keyframes.mjs.
 */
export function MvlpFeature({ project }: { project: Project }) {
  const shots = pickShots(project, ["home", "recipients", "eligibility"]);
  return (
    <div className="vf relative aspect-video overflow-hidden border border-rule">
      <div className="vf-wash absolute inset-0" aria-hidden="true" />
      <div className="vf-stage absolute inset-0">
        <div className="vf-brand absolute top-[9%] left-[6%] z-10 max-w-[52%]">
          <span className="vf-pill inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-2.5 py-1 font-mono text-[0.5625rem] tracking-[0.1em] text-zinc-400 uppercase sm:px-3 sm:py-1.5 sm:text-[0.625rem]">
            <span className="vf-dot block h-1.5 w-1.5 rounded-full bg-[#6b7be0]" aria-hidden="true" />
            Métis Veterans Legacy Program
          </span>
          <span className="mt-3 block font-sans text-[1.25rem] leading-[0.95] font-bold tracking-[-0.03em] sm:mt-4 sm:text-[2rem]">
            <span className="vf-line-1 block text-white">Honouring Our</span>
            <span className="vf-line-2 block text-zinc-500">Veterans Legacy</span>
          </span>
          <span className="vf-tag mt-4 hidden font-mono sm:block text-[0.6875rem] tracking-[0.08em] text-white/50 uppercase">
            Next.js + Strapi
          </span>
        </div>

        <div className="vf-art absolute inset-0" aria-hidden="true">
          {shots.map((img, i) => (
            <div key={img.src} className={`vf-window vf-window-${i + 1}`}>
              <Image
                src={img.src}
                alt=""
                width={img.width}
                height={img.height}
                sizes="(min-width: 768px) 360px, 70vw"
                loading="eager"
                className="h-auto w-full"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
